
# dijkstra__shortest__path
:toc:
:toclevels: 6

## dijkstra__shortest__path

### question

Implement "Dijkstra's Shortest Path First algorithm" .

#### algorithm

* an vertex represents one location
* an edge represents the connection from one vertex to another
* the value of an edge is the measure of the distance from one vertex to another

* (initialize)
** create many vertex one for each known location
** some one vertex is chosen as the starting vertex
** an initial edge is created for the starting vertex to every other vertex
** the initial edge of the starting vertex to itself has an 0 value
** the initial edge of the starting vertex to every other vertex has an infinite value

* (loop)
** the current vertex is the vertex with the minimal distance from the starting vertex
** the current vertex is removed

** obtain the distance from the current vertex to any known neighbor
*** (for each such neighbour)
*** the existing value is the value of the edge that is from the starting vertex to the vertex for the known neighbour
*** the potential value is the value of the edge that is from the starting vertex to the current vertex plus the distance from the current vertex to the known neighbour 
*** if that potential value is shorter than that existing value
**** update that edge from the starting vertex to the neighbour vertex with the potential value
**** update the predecessor of the neighbour vertex to be the current vertex
** goto (loop) unless all vertex have been removed

### answer

###### ./src/suite/dijkstra.prolog
```

:- [library(lists)] .

:- multifile data:distance/4 .

:- dynamic data:vertex/3 .
:- dynamic data:edge/4 .
:- dynamic data:predecessor/4 .

calculate(Q0)
:-
prolog:forall(location(Q0,START),calculate(Q0,START))
.

calculate(Q0,START0)
:-
create__initial__vertexes(Q0,START0) ,
create__initial__edges(Q0,START0) ,
create__initial__predecessors(Q0,START0) ,
loop(Q0,START0) .

debug
:-
prolog:listing(data:distance) ,
prolog:listing(data:vertex) ,
prolog:listing(data:edge) ,
prolog:listing(data:predecessor)
.

location(Q0,LOCATION)
:-
lookup(data:distance(Q0,LOCATION,_,_)) ;
lookup(data:distance(Q0,_,LOCATION,_))
.

neighbour(Q0,LOCATION_1,LOCATION_2,DISTANCE)
:-
lookup(data:distance(Q0,LOCATION_1,LOCATION_2,DISTANCE)) ;
lookup(data:distance(Q0,LOCATION_2,LOCATION_1,DISTANCE))
.

create__initial__vertexes(Q0,START0)
:-
location(Q0,LOCATION) ,
+ lookup(data:vertex(Q0,START0,LOCATION)) ,
remember(data:vertex(Q0,START0,LOCATION)) ,
fail ;
true
.

create__initial__edges(Q0,START0)
:-
lookup(data:vertex(Q0,START0,VERTEX)) ,
(START0 = VERTEX -> DISTANCE is 0 ; DISTANCE is inf) ,
+ lookup(data:edge(Q0,START0,VERTEX,DISTANCE)) ,
remember(data:edge(Q0,START0,VERTEX,DISTANCE)) ,
fail ;
true
.

create__initial__predecessors(Q0,START0)
:-
lookup(data:vertex(Q0,START0,VERTEX)) ,
+ lookup(data:predecessor(Q0,START0,VERTEX,_)) ,
remember(data:predecessor(Q0,START0,VERTEX,_)) ,
fail ;
true
.

loop(Q0,START0)
:-
repeat ,
current__vertex(Q0,START0,CURRENT,DISTANCE_FROM_START) ,
forget(data:vertex(Q0,START0,CURRENT)) ,
neighbour(Q0,CURRENT,NEIGHBOUR,DISTANCE_FROM_NEIGHBOUR) ,
POTENTIAL_DISTANCE is DISTANCE_FROM_START + DISTANCE_FROM_NEIGHBOUR ,
lookup(data:edge(Q0,START0,NEIGHBOUR,EXISTING_DISTANCE)) ,
maybe__update__neighbour(Q0,START0,CURRENT,NEIGHBOUR,EXISTING_DISTANCE,POTENTIAL_DISTANCE) ,
+ lookup(data:vertex(Q0,_,_)) , % repeat until no more vertex .
!
.

current__vertex(Q0,START0,CURRENT,DISTANCE_FROM_START)
:- % there is an edge for which no other edge has an lessor distance
lookup(data:vertex(Q0,START0,CURRENT)) ,
lookup(data:edge(Q0,START0,CURRENT,DISTANCE_FROM_START)) ,
+
(
	lookup(data:vertex(Q0,START0,OTHER)) ,
	lookup(data:edge(Q0,START0,OTHER,DISTANCE_COMPARE)) , 
	DISTANCE_COMPARE < DISTANCE_FROM_START
) ,
!  % only one current vertex at an time .
.

maybe__update__neighbour(Q0,START0,CURRENT0,NEIGHBOUR0,EXISTING_DISTANCE0,POTENTIAL_DISTANCE0)
:-
POTENTIAL_DISTANCE0 < EXISTING_DISTANCE0 ->
forget(data:edge(Q0,START0,NEIGHBOUR0,_)) ,
remember(data:edge(Q0,START0,NEIGHBOUR0,POTENTIAL_DISTANCE0)) ,
forget(data:predecessor(Q0,START0,NEIGHBOUR0,_)) ,
remember(data:predecessor(Q0,START0,NEIGHBOUR0,CURRENT0)) ;
true
.

path(Q0,START0,TARGET0,PATHs)
:-
path__of__predecessors(Q0,START0,TARGET0,REVERSE_PATHs) ,
! ,
lists:reverse(REVERSE_PATHs,PATHs)
.

path__of__predecessors(Q0,START0,TARGET0,PATHs)
:-
START0 = TARGET0 ->
PATHs = [segment(TARGET0,0)] ;
lookup(data:predecessor(Q0,START0,TARGET0,PREDECESSOR)) ,
lookup(data:edge(Q0,START0,TARGET0,DISTANCE)) ,
PATHs = [segment(TARGET0,DISTANCE)|PATHs0] ,
path__of__predecessors(Q0,START0,PREDECESSOR,PATHs0)
.

remember(TERM)
:-
prolog:assertz(TERM)
.

forget(TERM)
:-
prolog:retractall(TERM)
.

lookup(TERM)
:-
prolog:call(TERM)
.
```

#### bonus

_Allow for an new table to be loaded from an csv file_ .

###### ./data/rosetta.csv
```
"","a","b","c","d","e","f"
"a","","7","9","d","","14"
"b","","","10","15","",""
"c","","","","11","","2"
"d","","","","","6",""
"e","","","","","","9"
"f","","","","","",""
```

###### ./src/suite/csv.prolog
```

:- [library(csv)] .
:- [library(lists)] .

:- op(1,'xfy','csv_') .


%! csv(FILE0)
%
% read the CSV file `FILE0` and add facts to the database .

csv(FILE0)
:-
(start) csv_ (FILE0)
.

(start) csv_ (FILE0)
:-
csv:csv_read_file(FILE0,[HEADER|ROWss]) ,
row__to__list(HEADER,HEADERs) ,
(loop) csv_ (FILE0,HEADERs,ROWss) 
.

(loop) csv_ (_FILE0,_HEADERs,[]) 
:-
true
.

(loop) csv_ (FILE,HEADERs,[ROW|ROWss]) 
:-
row__to__list(ROW,ROWs) ,
lists:nth1(1,ROWs,LOCATION_A) ,
QUERY_A=(lists:nth1(NTH,ROWs,DISTANCE)) ,
QUERY_B=(NTH > 1) ,
QUERY_C=(lists:nth1(NTH,HEADERs,LOCATION_B)) ,
QUERY=(QUERY_A,QUERY_B,QUERY_C) ,
ASSERT=(prolog:number(DISTANCE) -> remember(data:distance(FILE,LOCATION_A,LOCATION_B,DISTANCE)) ; true) ,
forall(QUERY,ASSERT) ,
(loop) csv_ (FILE,HEADERs,ROWss) 
.

row__to__list(ROW,ROWs)
:-
ROW=..[_|ROWs]
.

```

###### ./src/suite/csv.prolog.demo
```
/*
?- FILE='data/rosetta.csv' , csv(FILE) , calculate(FILE) , path(FILE,'a','e',PATHs) . 
FILE = 'data/rosetta.csv' ,
PATHs = [segment(a,0),segment(c,9),segment(f,11),segment(e,20)] .

?- FILE='data/rosetta.csv' , csv(FILE) , calculate(FILE) , path(FILE,'a','f',PATHs) .

FILE = 'data/rosetta.csv' ,
PATHs = [segment(a,0),segment(c,9),segment(f,11)] .

?- 
*/
```

## appendix

### authorship

* (c) kintalken@gmail.com 2020-11-01 .
