
# dijkstra__shortest__path
:toc:
:toclevels: 6

## dijkstra__shortest__path

### question

Implement "Dijkstra's Shortest Path First algorithm" .

#### algorithm

* an vertex represents one location
* an edge represents the connection from one vertex to another
* the value of an edge is the measure of the distance from one vertex to another

* (initialize)
** create many vertex one for each known location
** some one vertex is chosen as the starting vertex
** an initial edge is created for the starting vertex to every other vertex
** the initial edge of the starting vertex to itself has an 0 value
** the initial edge of the starting vertex to every other vertex has an infinite value

* (loop)
** the current vertex is the vertex with the minimal distance from the starting vertex
** the current vertex is removed

** obtain the distance from the current vertex to any known neighbor
*** (for each such neighbour)
*** the existing value is the value of the edge that is from the starting vertex to the vertex for the known neighbour
*** the potential value is the value of the edge that is from the starting vertex to the current vertex plus the distance from the current vertex to the known neighbour 
*** if that potential value is shorter than that existing value
**** update that edge from the starting vertex to the neighbour vertex with the potential value
**** update the predecessor of the neighbour vertex to be the current vertex
** goto (loop) unless all vertex have been removed

### answer

###### ./src/suite.prolog
```
:- ['./suite/dijkstra.prolog'] .
:- ['./suite/csv.prolog'] .
:- ['./suite/demo_1.prolog'] .
:- ['./suite/demo_2.prolog'] .

```

#### bonus

_Allow for an new table to be loaded from an csv file_ .

###### ./data/rosetta.csv
```
"","a","b","c","d","e","f"
"a","","7","9","d","","14"
"b","","","10","15","",""
"c","","","","11","","2"
"d","","","","","6",""
"e","","","","","","9"
"f","","","","","",""
```

###### ./src/suite/csv.prolog
```

:- [library(csv)] .
:- [library(lists)] .

:- op(1,'xfy','csv_') .


%! csv(FILE0)
%
% read the CSV file `FILE0` and add facts to the database .

csv(FILE0)
:-
(start) csv_ (FILE0)
.

(start) csv_ (FILE0)
:-
csv:csv_read_file(FILE0,[HEADER|ROWss]) ,
row__to__list(HEADER,HEADERs) ,
(loop) csv_ (FILE0,HEADERs,ROWss) 
.

(loop) csv_ (_FILE0,_HEADERs,[]) 
:-
true
.

(loop) csv_ (FILE,HEADERs,[ROW|ROWss]) 
:-
row__to__list(ROW,ROWs) ,
lists:nth1(1,ROWs,LOCATION_A) ,
QUERY_A=(lists:nth1(NTH,ROWs,DISTANCE)) ,
QUERY_B=(NTH > 1) ,
QUERY_C=(lists:nth1(NTH,HEADERs,LOCATION_B)) ,
QUERY=(QUERY_A,QUERY_B,QUERY_C) ,
ASSERT=(prolog:number(DISTANCE) -> remember(data:distance(FILE,LOCATION_A,LOCATION_B,DISTANCE)) ; true) ,
forall(QUERY,ASSERT) ,
(loop) csv_ (FILE,HEADERs,ROWss) 
.

row__to__list(ROW,ROWs)
:-
ROW=..[_|ROWs]
.

/*
?- csv('data/rosetta.csv') .

?- listing(data:distance) .

?-
*/

```

##### demo
```
```

## appendix

### authorship

* (c) kintalken@gmail.com 2020-11-01 .
